  set -g history-limit 100000

  # Scroll myszką wchodzi w copy-mode i przewija bufor tmuxa
  bind -T root WheelUpPane if-shell -F '#{alternate_on}' \
    'send-keys -M' \
    'copy-mode -e; send-keys -X scroll-up'

  bind -T root WheelDownPane if-shell -F '#{pane_in_mode}' \
    'send-keys -X scroll-down' \
    'send-keys -M'


