  set -g history-limit 100000
  set -g allow-passthrough on
  set -s extended-keys on
  set -s extended-keys-format xterm

  # Gruvbox dark colors
  set -g status-style 'bg=#282828,fg=#ebdbb2'
  set -g status-left-style 'bg=#689d6a,fg=#282828,bold'
  set -g status-right-style 'bg=#282828,fg=#a89984'
  set -g window-status-style 'bg=#282828,fg=#a89984'
  set -g window-status-current-style 'bg=#d79921,fg=#282828,bold'
  set -g pane-border-style 'fg=#504945'
  set -g pane-active-border-style 'fg=#d79921'
  set -g message-style 'bg=#3c3836,fg=#ebdbb2'
  set -g mode-style 'bg=#458588,fg=#282828,bold'

  # Scroll myszką wchodzi w copy-mode i przewija bufor tmuxa
  bind -T root WheelUpPane if-shell -F '#{alternate_on}' \
    'send-keys -M' \
    'copy-mode -e; send-keys -X scroll-up'

  bind -T root WheelDownPane if-shell -F '#{pane_in_mode}' \
    'send-keys -X scroll-down' \
    'send-keys -M'

