name: Secret and Sensitive Data Scanning

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  secret-scanning:
    uses: bajor/github-workflows/.github/workflows/secret-scanning.yml@main
